version: '3.9'
services:
  app:
    image: ghcr.io/realsakibuddinmahmud/dea-app:${IMAGE_TAG:-latest}
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    ports:
      - "8080:80"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: landlord_master
    command: ["--default-authentication-plugin=mysql_native_password"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-psecret"]
      interval: 10s
      timeout: 5s
      retries: 10

