name: SBOM

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0.17.6

      - name: Generate SBOM (SPDX JSON)
        run: |
          ./syft dir:. -o spdx-json > sbom.spdx.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json

